### ISSUE TITLE
Get CircleCI "Apply" to run

### ISSUE THREAD

**Issue by esacteksab** [limnh/journey#12]
Given `terraform init` or `terraform plan` runs on staging/PR, we need `terraform apply` to run on Master (merge to master). Make the necessary changes to `.circle/config.yaml` so that it runs `terraform apply` with the plan created in the previous steps/stages.

**Comment by limnh** [comment]
has been successfully implemented with the following code:

```<<: *default_config
  steps:
    - *restore_repo
    - *set_terraform_environment
    - *terraform_init
    - attach_workspace:
        at: *working_directory
    - run:
        name: terraform apply
        command: |
          source $BASH_ENV
          pwd
          ls -al
          cd packet/builder && terraform apply --auto-approve terraform.plan
```

additional context available in #14
